### ISSUE TITLE
【备忘清单】 请求: 可以添加开箱即用的函数吗？例如：变量名格式转换（下划线转驼峰、驼峰转下划线这类的）

### ISSUE THREAD

**Issue by 13812700839** [jaywcjlove/reference#101]
您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的备忘清单(速查表)。

【请您在这里介绍一下工具或者语言，这很重要】

- [ ] 如果你有一张不错的备忘清单(速查表) [`参考这里`](https://github.com/jaywcjlove/reference/blob/main/CONTRIBUTING.md) 为仓库贡献。
- [ ] 如果您不方便贡献，请在下方参考资料中提供链接地址，方便共建备忘清单(速查表)
- [x] 这里为您提供了 Markdown 排版[示例教程](https://jaywcjlove.github.io/reference/docs/quickreference.html)

#### 提供参考资料地址

提供更多参考资料有助于我们整理成备忘清单(速查表)

- 提供参考地址 https://jaywcjlove.github.io/reference
- 提供官网地址 https://jaywcjlove.github.io/reference

_⚠️ 注意: 随着内容越来越多，可能甚至找不到这个工具或者语言的官网，请您在这里提供以便大家共同参与贡献内容_

**Comment by jaywcjlove** [comment]
@13812700839 没有理解，是弄个清单提供一些函数命名？

**Comment by 13812700839** [comment]
就是提供一些常用函数，可以直接使用的

**Comment by 13812700839** [comment]
@jaywcjlove 对的，因为我现在就有遇到这种问题，Java代码实现了，但让我使用JavaScript去实现的时候，就需要去翻找对应的资料，这工作量很大，但可以共建，有人想到哪个就可以提出来添加进去

**Comment by jaywcjlove** [comment]
@13812700839 你把另外一个项目规划进来了，这样话一个页面承载不下。
https://www.30secondsofcode.org/

中文：https://www.html.cn/30-seconds-of-code/

**Comment by 13812700839** [comment]
@jaywcjlove 欧克欧克，原来是分开了，那我这没问题了

**Comment by 13812700839** [comment]
@jaywcjlove 这个项目主要是以语法为主是吧

**Comment by jaywcjlove** [comment]
@13812700839  主要是入门语法，api，命令参数参考清单

**Comment by jaywcjlove** [comment]
还提供一些基础性常用的示例参考，那也是 API 的实例，如果常用方法，那实在太多了，一页放不下

**Comment by 13812700839** [comment]
好的好的，我了解了
