### ISSUE TITLE
错误报告: cs.md 前端页面换行看上去不太对

### ISSUE THREAD

**Issue by qyl27** [jaywcjlove/reference#153]
### 错误类型

- [x] 排版 & 文字错误
- [ ] 清单内容示例错误

### 错误清单

`cs.md`

### 错误内容描述

前端页面换行看上去不太对，很多代码行，都在单词内部被截断了。
这样子可能带来一些使用上的不便。

建议的解决方案：
1. 加行号
2. 不要在单词内部换行
3. 或者干脆不要自动换行

**Comment by jaywcjlove** [comment]
已更新部分内容，可以在 #66 中讨论
