### ISSUE TITLE
搜索优化建议：搜索 "c" 时 css 的优先级应该比 C语言低

### ISSUE THREAD

**Issue by mofelee** [jaywcjlove/reference#159]
<img width="1071" alt="CleanShot 2022-11-21 at 15 29 05@2x" src="https://user-images.githubusercontent.com/5069410/202990369-6334e2bc-64c3-4fba-a079-a0f59a84a4ef.png">

**Comment by mofelee** [comment]
试过 fuse 将 https://github.com/jaywcjlove/reference/blob/main/scripts/js/main.js#L44 改为100效果会好一些

具体多少还是要调试一下

**Comment by jaywcjlove** [comment]
@mofelee 好像没有必要设置那么大

**Comment by mofelee** [comment]
> @mofelee 好像没有必要设置那么大

是的，搜索需要校调一下
