### ISSUE TITLE
错误报告: build 后搜索展示有问题

### ISSUE THREAD

**Issue by 92000** [jaywcjlove/reference#161]
### 错误类型

- [ ] 排版 & 文字错误
- [ ] 首页搜索相关

### 错误内容描述

使用 v1.24.0 npm run build
搜索相关有问题，
首页打开搜索，列表清单是空的。

**Comment by jaywcjlove** [comment]
@92000 亦什么错误信息？

**Comment by 92000** [comment]
@jaywcjlove 
![This is an image](https://m.360buyimg.com/babel/jfs/t1/91169/11/33010/19887/637b4ab6E79b9110b/9c49170476628fcd.png)

**Comment by jaywcjlove** [comment]
@92000 在Windows上？我测试一下windows

**Comment by jaywcjlove** [comment]
@92000 用 CI 测试了build可以显示了

**Comment by 92000** [comment]
@jaywcjlove  感谢
更新到最新可以查询搜索了。
https://quickref.aibk.cn/

**Comment by jaywcjlove** [comment]
@92000 已经将你的网站放到首页了 #102
