### ISSUE TITLE
错误报告: https://wangchujiang.com/reference/data.json ，未生成 data.json 文件！

### ISSUE THREAD

**Issue by mofelee** [jaywcjlove/reference#173]
<img width="623" alt="CleanShot 2022-11-26 at 09 16 50@2x" src="https://user-images.githubusercontent.com/5069410/204067020-e1d06d4a-2326-4dbe-92ed-8febc25c7a0f.png">

**Comment by mofelee** [comment]
https://github.com/jaywcjlove/reference/tree/gh-pages

这个分支怎么只有data.js了。

**Comment by jaywcjlove** [comment]
@mofelee 不好意思，我将脚本放到一个新仓库维护，导致的bug 已经修复稍后我更新一下就有了

**Comment by mofelee** [comment]
嗯嗯，已经修复了
