### ISSUE TITLE
请求添加备忘清单: C# .NET or core

### ISSUE THREAD

**Issue by chatxxsc** [jaywcjlove/reference#227]
说明项目
csharp 代码片段 有关键词表单在里面

提供参考资料地址
https://github.com/andredarcie/csharp-quick-reference-guide

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/reference/blob/main/docs/cs.md
@chatxxsc 这个应该是的吧。

**Comment by jaywcjlove** [comment]
- #66
