### ISSUE TITLE
在aarch64架构服务器上使用docker部署遇到问题

### ISSUE THREAD

**Issue by 750624391** [jaywcjlove/reference#232]
使用docker部署时出现容器无法启动的情况，查看日志发现以下错误：

exec /busybox: exec format error

**Comment by jaywcjlove** [comment]
@750624391 不确定怎么支持，但是我加上了 `linux/arm64/v7` 的支持，你可以试一试。

https://github.com/jaywcjlove/reference/blob/247cd4d4e6d2934f23cab590d98f2d80257dcc30/.github/workflows/ci.yml#L138

**Comment by 750624391** [comment]
经过测试后发现该问题源于镜像 `lipanski/docker-static-website:latest` 无法在aarch64架构上运行，我的解决方案是启动nginx服务，将dist内容放入容器中，最后打包一个新的镜像

**Comment by jaywcjlove** [comment]
那这样子不好解决，我希望保持最小镜像 @750624391

**Comment by sgzman** [comment]
> 那这样子不好解决，我希望保持最小镜像 @750624391

请问现在有新的解决办法了吗？我也想部署在aarch64上
