### ISSUE TITLE
请求添加备忘清单: Telegram频道

### ISSUE THREAD

**Issue by youyouoiloil** [jaywcjlove/reference#249]
是否开一个收录 Telegram 频道的目录
**油油分享频道**
分享开源、优秀的软件，有趣、实用的网站资源
https://t.me/youyousharechannel

**频道藏馆**
收藏TG频道、群组、机器人
https://t.me/channelhall

**Comment by jaywcjlove** [comment]
@youyouoiloil 感觉直接能把镜像网站干没了
