### ISSUE TITLE
使用 Command + k 搜索, 会多输入一个k在搜索框

### ISSUE THREAD

**Issue by zxx-457** [jaywcjlove/reference#279]
### 错误类型

- [ ] 排版 & 文字错误
- [ ] 清单内容示例错误
- [x] 功能错误 

### 错误内容描述
系统 Linux 
浏览器 Vivaldi
Command 对应的 Gui 键, 也就是 Win 键

**问题 :** 
+ Command + K 打开搜索框, 会多输入一个k 在搜索框里面

**其他建议 :**
+ Ese 可以清空搜索框的输入, 再关闭搜索框
+ 第一次打开可以根据系统识别是亮色还是暗色主题

**Comment by jaywcjlove** [comment]
@zxx-457 

> Command + K 打开搜索框, 会多输入一个k 在搜索框里面

这个问题我在 mac 上面没有测试出任何问题，你的环境没有办法测试

> Ese 可以清空搜索框的输入, 再关闭搜索框

已经更改

> 第一次打开可以根据系统识别是亮色还是暗色主题

如果你不点击切换主题，就是根据系统来识别的

**Comment by zxx-457** [comment]
Command + K 的问题, 我用 Chrome 试了试, 也是一个样的问题. 

用 Firefox 的时候是没法快捷键呼出搜索.

这个Command 键不应该对应Linux 键盘的 Alt 键吗, 怎么会是 GUI 键

**Comment by jaywcjlove** [comment]
@zxx-457 `metaKey` 在 `Windows` 键盘中是 `Windows`键，在苹果机中是 command 键，在Linux 上是不是 `Windows` 键 ？

**Comment by jaywcjlove** [comment]
@zxx-457 已经支持 <kbd>ctrl</kbd>+<kbd>k</kbd>

**Comment by zxx-457** [comment]
> @zxx-457 已经支持 ctrl+k

ctrl 测试可以用 谢谢
