### ISSUE TITLE
错误报告: 1.36.0版本下载不了,提示not found

### ISSUE THREAD

**Issue by xuezh01** [jaywcjlove/reference#308]
1.36.0版本下载不了,提示not found

**Comment by jaywcjlove** [comment]
? @xuezh01 下载什么？

**Comment by xuezh01** [comment]
> 

release里的源码zip,还有直接git clone也不行

**Comment by jaywcjlove** [comment]
@xuezh01 这我帮不了你，可能你需要🪜，或者[****](https://github.com/docmirror/dev-sidecar)
