### ISSUE TITLE
【备忘清单】 请求: Tmux

### ISSUE THREAD

**Issue by yanxiang-wang** [jaywcjlove/reference#33]
您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的备忘清单(速查表)。

tmux is an open-source terminal multiplexer for Unix-like operating systems. It allows multiple terminal sessions to be accessed simultaneously in a single window. It is useful for running more than one command-line program at the same time.

#### 提供参考资料地址

提供更多参考资料有助于我们整理成备忘清单(速查表)

- 提供参考地址 https://tmuxcheatsheet.com/
- 提供官网地址 https://github.com/tmux/tmux

**Comment by jaywcjlove** [comment]
@yanxiang-wang 已添加欢迎补充
