### ISSUE TITLE
错误报告: vim.md

### ISSUE THREAD

**Issue by EUye9IM** [jaywcjlove/reference#342]
### 错误类型

- [x] 排版 & 文字错误
- [ ] 清单内容示例错误

### 错误清单

`docs/vim.md`

### 错误内容描述

187 行 `\`<C-v>\`     | 进入可视化阻挡模式`

应是 `\`<C-v>\`     | 进入可视块模式`

虽然block可以是阻挡的意思但是，，但是！为什么会被翻译成阻挡啊？！

**Comment by EUye9IM** [comment]
或许不应该标bug的label，，，麻烦所有者自己改一下了我好像没法再编辑了

**Comment by jaywcjlove** [comment]
@EUye9IM 你可以 fork 进行编辑提交 PR

**Comment by jaywcjlove** [comment]
@EUye9IM 已经修改
