### ISSUE TITLE
错误报告: JavaScript

### ISSUE THREAD

**Issue by NormalFrank1** [jaywcjlove/reference#347]
### 错误类型

- [ x] 排版 & 文字错误
- [ ] 清单内容示例错误

### 错误清单
const myMath = require('./myMath.js')
`xxx.md`

### 错误内容描述

应该最后加上；结尾吧。

**Comment by jaywcjlove** [comment]
@NormalFrank1 没有明白你说的什么错误

**Comment by jaywcjlove** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/1680273/233003423-da9bd1aa-36b8-4269-b215-aad3947f6f20.png">

@NormalFrank1 你指的是这个是吧，这并没有错误，如果你说的是如上截图没有在结尾添加 **分号** 。

**Comment by jaywcjlove** [comment]
@NormalFrank1 如果你有强迫症，欢迎提交 PR
