### ISSUE TITLE
【备忘清单】 请求: 

### ISSUE THREAD

**Issue by rshcbxf52** [jaywcjlove/reference#354]

**Comment by rshcbxf52** [comment]
1. 手把手指导你写垃圾代码！从入门到精通！
 https://github.com/trekhleb/state-of-the-art-shitcode/blob/master/README.zh-CN.md
备用：https://kgithub.com/trekhleb/state-of-the-art-shitcode/blob/master/README.zh-CN.md

2. PyDebloatX、一键卸载 Windows 默认程序
https://github.com/Teraskull/PyDebloatX
备用：https://kgithub.com/Teraskull/PyDebloatX

3. Carbon、源码转图片
https://github.com/carbon-app/carbon
备用：https://kgithub.com/carbon-app/carbon

4. Alist、存储聚合
https://github.com/alist-org/alist
备用：https://kgithub.com/alist-org/alist

5. FinancialSupportForOpenSource、开源挣钱手册
https://github.com/wizicer/FinancialSupportForOpenSource
备用：https://kgithub.com/wizicer/FinancialSupportForOpenSource

6. AutoCut、通过字幕剪视频
https://github.com/mli/autocut
备用：https://kgithub.com/mli/autocut

Windows直接使用的版本：https://github.com/zcf0508/autocut

7. Image-to-Braille、图片转字符
https://github.com/505e06b2/Image-to-Braille
备用：https://kgithub.com/505e06b2/Image-to-Braille

体验网址：https://505e06b2.github.io/Image-to-Braille/

8. Notion风格头像
https://github.com/Mayandev/notion-avatar
备用：https://kgithub.com/Mayandev/notion-avatar

9. Magic-Copy、浏览器快速抠图插件
https://github.com/kevmo314/magic-copy
备用：https://kgithub.com/kevmo314/magic-copy

10. Reference、代码速查表
https://github.com/jaywcjlove/reference
备用：https://kgithub.com/jaywcjlove/reference

**Comment by jaywcjlove** [comment]
@rshcbxf52 ?
