### ISSUE TITLE
🐞 错误报告: xxx.md

### ISSUE THREAD

**Issue by Hopetree** [jaywcjlove/reference#380]
### 📄 错误清单

Dockerfile

### 🧨 错误类型

- [ ] 排版 & 文字错误
- [ ] 清单内容示例错误
- [X] 其它

### 📖 错误说明

作者你为啥Dockerfile不是直接写的打包的方式而是直接去拉你的镜像？
我发现我用docker去打镜像的时候老是少文件，执行完npm run build发现dist里面根本没有docs目录，在本地倒是好的，找了半天不知道原因，下面是我的dockerfile
```
FROM node:14-alpine AS stage
WORKDIR /opt/build
COPY package*.json ./
RUN npm install --verbose
COPY . .
RUN echo 'REF_URL=https://tendcode.com/\nREF_LABEL=网站首页' > .env && ls -a
RUN npm run build && ls -a dist

FROM nginx:stable-alpine
COPY --from=stage /opt/build/dist /usr/share/nginx/html
```

**Comment by jaywcjlove** [comment]
@Hopetree 你在  `COPY . .` 的时候查看是不是有文件没有拷贝进去

**Comment by Hopetree** [comment]
@jaywcjlove 文件是都拷贝进去了，而且index是正常生成可以正常访问，就是docs文件没有了，data.json也没有，具体生成的你可以看看我执行构建的日志：
```
Step 5/9 : COPY . .
 ---> db0261cf0be4
Step 6/9 : RUN echo 'REF_URL=https://tendcode.com/\nREF_LABEL=网站首页' > .env && ls -a
 ---> Running in 083c79d54468
.
..
.dockerignore
.editorconfig
.env
.git
.gitattributes
.gitignore
.lintstagedrc
.markdownlint.json
.npmrc
.prettierignore
.prettierrc
.refsrc.json
CONTRIBUTING.md
Dockerfile
LICENSE
README.md
assets
docker-compose.yml
node_modules
package-lock.json
package.json
renovate.json
Removing intermediate container 083c79d54468
 ---> 03c5e35cb992
Step 7/9 : RUN npm run build && ls -a dist
 ---> Running in b598d6766aef

> @wcj/reference@1.37.0 build /opt/build
> refs-cli

♻️  index.html 
 
 done!

.
..
data.js
index.html
js
style
Removing intermediate container b598d6766aef
 ---> 3e19eb47c63a
Step 8/9 : FROM nginx:stable-alpine
```

**Comment by jaywcjlove** [comment]
@Hopetree  `COPY ./docs .` 试一下？

**Comment by jaywcjlove** [comment]
@Hopetree https://github.com/jaywcjlove/reference/blob/3cc761446ee7fafd0744c720299559374898e088/.dockerignore#L3

我知道问题了，我的 docker file, 是 将编译后的 静态资源拷贝进去，你的是在 docker 中编译

**Comment by Hopetree** [comment]
@jaywcjlove 知道原因了，是因为你的.dockerignore加了忽略docs的规则，所以的确是docs没有copy过去，这个你是不是应该删除一下啊，可以关闭了这个issues

**Comment by jaywcjlove** [comment]
其实我这个里面只拷贝静态资源[.dockerignore](https://github.com/jaywcjlove/reference/blob/3cc761446ee7fafd0744c720299559374898e088/.dockerignore#L3) 应该是没有用的感觉
