### ISSUE TITLE
npm i报错

### ISSUE THREAD

**Issue by danerlt** [jaywcjlove/reference#4]
### npm安装依赖报错
node版本：v16.13.1
npm版本： 8.1.2

### 错误清单

![image](https://user-images.githubusercontent.com/14197717/193173533-6af20dc6-f5ac-4667-a283-98a3a5a3a50c.png)

### 错误内容描述
我想在本地运行项目，使用 `npm i`安装依赖报错，错误输出如上图。

**Comment by jaywcjlove** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/1680273/193295143-653f0943-c784-4eb1-a74d-34d09cba0ee5.png">

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/1680273/193295385-7604a5e8-ed29-4148-a57e-50adba1444a3.png">

@danerlt 没有报错， nodejs 版本太低？包也有这个版本啊
