### ISSUE TITLE
【备忘清单】 请求: R

### ISSUE THREAD

**Issue by lundermatin** [jaywcjlove/reference#410]
### 说明项目

R语言是一种广泛用于统计分析和数据可视化的编程语言。它由新西兰奥克兰大学的罗斯·伊哈卡和罗伯特·杰特曼开发，并于1995年首次发布。R语言的设计目标是提供一个灵活的、可扩展的统计计算环境，使数据分析师、统计学家和研究人员能够更轻松地处理和分析数据。

### 提供官网

https://www.r-project.org/

### 参考资料 URL

https://rdrr.io/
https://www.rdocumentation.org/

**Comment by zhangjinweiboy** [comment]
1

**Comment by zhangjinweiboy** [comment]
+1

**Comment by zhangjinweiboy** [comment]
R语言主要用于统计分析、建模以及可视化，其中的统计包非常多且强大。

**Comment by ButterBartel3C3A** [comment]
+1

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/reference/issues/285
