### ISSUE TITLE
🐞 错误报告: nginx.md 排版及示例错误

### ISSUE THREAD

**Issue by ohto-ai** [jaywcjlove/reference#446]
### 📄 错误清单

`docs/nginx.md`

### 🧨 错误类型

- [X] 排版 & 文字错误
- [X] 清单内容示例错误
- [ ] 其它

## L274-L286 静态资源 示例错误
[docs/nginx.md#L274-L286](https://github.com/jaywcjlove/reference/blame/d4b984c509344b81774902c829ba1e9f83a73fb1/docs/nginx.md#L274-L286)
```nginx
server {
  listen 80;
  server_name example.com;
  root /path/to/website;
  # root /www/data/ 示例，如果里面没有'root'，它将寻找 /www/data/index.html
  location / {
  }
  location /images/ { # 如果里面没有“root”，它将寻找 /www/data/images/index.html
  }
  location /videos/ { # 由于里面有“root”，它会寻找 /www/media/videos/index.html
      root /www/media;
  }
}
```
`location /`和`location /images/`的注释与其实际效果不同，因为外层的`root`为`/path/to/website`，此处的搜索路径应为`/path/to/website/`和`/path/to/website/images/`

----------

## L513 负载均衡示例 排版错误
[docs/nginx.md#L513](https://github.com/jaywcjlove/reference/blame/d4b984c509344b81774902c829ba1e9f83a73fb1/docs/nginx.md#L513)
```nginx
server 127.0.0.1:85 weight=4;;
```

**Comment by jaywcjlove** [comment]
@ohto-ai 其实也没有错，因为注释前面有个 `root /www/data/ 示例`， 我改成一样了

L513 负载均衡示例 排版错误， 是什么意思？

**Comment by ohto-ai** [comment]
> @ohto-ai 其实也没有错，因为注释前面有个 `root /www/data/ 示例`， 我改成一样了
> 
> L513 负载均衡示例 排版错误， 是什么意思？

不好意思，L513忘记说明了，此处分号重复了

**Comment by jaywcjlove** [comment]
@ohto-ai 已修改，换衣提交 PR
