### ISSUE TITLE
Rewrite about rust

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [jaywcjlove/reference#49]
https://github.com/jaywcjlove/reference/blob/72d3bd8d42aa64fbdfbaf8c6fc966bb3c0262254/docs/rust.md?plain=1#L780-L815

@jaywcjlove 我想重新写一下 rust 文档，这部分感觉完全没有用，还有上面的**流程控制**，应该把**模式匹配**剥离出来

**Comment by jaywcjlove** [comment]
@Jack-Zhang-1314 可以的，重新优化排版布局

**Comment by jaywcjlove** [comment]
#49
