### ISSUE TITLE
【备忘清单】 请求: <vim>

### ISSUE THREAD

**Issue by fai666** [jaywcjlove/reference#574]
### 说明项目

申请加个 vim 编辑器的用法
Linux下的vim编辑器，运维编译环境搭建比较常用到

### 提供官网

https://www.vim.org/

### 参考资料 URL

https://zhuanlan.zhihu.com/p/68111471
https://www.runoob.com/linux/linux-vim.html
https://www.python100.com/html/SM1F511EH6B6.html

**Comment by fai666** [comment]
在https://github.com/jaywcjlove/linux-command中看到有vi了

**Comment by jaywcjlove** [comment]
@fai666 这里也有 https://wangchujiang.com/reference/docs/vim.html

**Comment by jaywcjlove** [comment]
<img width="1491" alt="image" src="https://github.com/jaywcjlove/reference/assets/1680273/eeae2197-5d97-46bd-9da7-91a8ffe13ab3">
