### ISSUE TITLE
【备忘清单】 请求:  Github Action

### ISSUE THREAD

**Issue by maplepie** [jaywcjlove/reference#612]
### 说明项目

请求添加Github Action速查清单

### 提供官网

https://github.com/

### 参考资料 URL

https://github.com/actions

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/reference/blob/187fe9e8c030597335592fb76c96ad0199571012/docs/github-actions.md?plain=1#L1-L37

已添加 @maplepie 

https://wangchujiang.com/reference/docs/github-actions.html

**Comment by maplepie** [comment]
666
