### ISSUE TITLE
【备忘清单】 请求: echarts

### ISSUE THREAD

**Issue by muzhuyutou** [jaywcjlove/reference#620]
### 说明项目

echarts是一个基于 JavaScript 的开源可视化图表库

### 提供官网

https://echarts.apache.org/zh/api.html#echarts

### 参考资料 URL

https://echarts.apache.org/zh/api.html#echarts

**Comment by zcyc** [comment]
同 #318

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/reference/issues/318
