### ISSUE TITLE
🐞 错误报告: Vim 备忘清单.md

### ISSUE THREAD

**Issue by coobin** [jaywcjlove/reference#625]
### 📄 错误清单

Vim 备忘清单

### 🧨 错误类型

- [X] 排版 & 文字错误
- [ ] 清单内容示例错误
- [ ] 其它

### 📖 错误说明

Vim 搜索和替换的板块中，/代表向后搜索，？代表向前搜索，这两个写反了。

**Comment by jaywcjlove** [comment]
@coobin 感谢，我找了半天😄，希望直接甩个 PR :)

**Comment by coobin** [comment]
谢谢～不太会用，下次知道了。

On Apr 24, 2024, at 15:00, 小弟调调 ***@***.***> wrote:



@coobin<https://github.com/coobin> 感谢，我找了半天😄，希望直接甩个 PR :)

**Comment by jaywcjlove** [comment]
@coobin 不会用没有关系的，动手试一下，你就会了，又比昨天进步了一点点
