### ISSUE TITLE
🐞 错误报告: https://github.com/jaywcjlove/reference/commit/3b0416a2c3b1622a6c4ec75e068d2154d7b0d5e5

### ISSUE THREAD

**Issue by wsqstar** [jaywcjlove/reference#664]
### 📄 错误清单

https://github.com/jaywcjlove/reference/commit/3b0416a2c3b1622a6c4ec75e068d2154d7b0d5e5

### 🧨 错误类型

- [ ] 排版 & 文字错误
- [ ] 清单内容示例错误
- [X] 其它

### 📖 错误说明

之前的同步脚本正常，但是周三开始报错了。
检查了一下时间 刚好是 https://github.com/jaywcjlove/reference/commit/3b0416a2c3b1622a6c4ec75e068d2154d7b0d5e5 导致了报错
下面是我部署的：

![image](https://github.com/jaywcjlove/reference/assets/24500520/86925971-2659-4bae-9642-81b336c62f1b)

**Comment by jaywcjlove** [comment]
@wsqstar 你的错误是 `aormsby/Fork-Sync-With-Upstream-action@v3.4` 发出来的错误

```
Pushing synced data to target branch.
To https://github.com/wsqstar/reference.git
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/wsqstar/reference.git'
ERROR:  exit 1
Could not push changes to target repo.
Try running in test mode to verify your action input. If that does not help, please open an issue.
Resetting git config to previous settings.
```

（拒绝允许 GitHub 应用程序在没有“workflows”权限的情况下创建或更新工作流“.github/workflows/ci.yml”）


我发现我的CI一直没有成功报错，我升级了我自己的 action，并设置了创建tag 的参数，CI才跑成功，我可能认为，GitHub API权限变了，CI 在我这里工作非常好

```
Run ncipollo/release-action@v1
Error: Error 422: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

<img width="1294" alt="image" src="https://github.com/jaywcjlove/reference/assets/1680273/ce0b9575-9242-4926-b8c5-09b3f0939546">


<img width="824" alt="image" src="https://github.com/jaywcjlove/reference/assets/1680273/62991083-2cfe-4633-ba34-1189d423b9ce">
