### ISSUE TITLE
🐞 错误报告: vim.md

### ISSUE THREAD

**Issue by Ruikoto** [jaywcjlove/reference#787]
### 📄 错误清单

docs/vim.md

### 🧨 错误类型

- [X] 排版 & 文字错误
- [ ] 清单内容示例错误
- [ ] 其它

### 📖 错误说明

截图所示段落未对齐。使用Chrome最新版浏览器，Windows11，未使用一些修改字体css等网页自定义工具。

![image](https://github.com/jaywcjlove/reference/assets/30781137/4953c33e-4cba-4d7e-9ac0-ab0d70bf4246)
![image](https://github.com/jaywcjlove/reference/assets/30781137/49374031-5f30-4207-bfd7-6963b15ffce4)

**Comment by jaywcjlove** [comment]
@Ruikoto 你这怎么解决，好像真的没有对齐哦

<img width="420" alt="image" src="https://github.com/jaywcjlove/reference/assets/1680273/9765d4c2-1e7d-45ab-ba6a-638a3bccfa9d">

**Comment by Ruikoto** [comment]
可能是我这的环境问题，我再排查一下

**Comment by a15355447898a** [comment]
<img width="1910" height="754" alt="Image" src="https://github.com/user-attachments/assets/482c26da-779e-4390-88c4-b1acc98b97d5" />

相同问题 在linux zen浏览器(fork版的firefox) 上可以看到

已经打开隐私窗口 只有bitwarden一个插件 没有别的影响字体的插件工具

刚刚更新的docker镜像
