### ISSUE TITLE
【备忘清单】 请求: <Name>

### ISSUE THREAD

**Issue by chen-bao-x** [jaywcjlove/reference#823]
### 说明项目

Symbbol Code 备忘录清单  扩充 键盘按键符号.

在写 软件使用指南 | 帮助文档 的时候经常会提到使用快捷键.
 
我这里提供几个常用的 快捷键符号.

| key | name          |
| --- | ------------- |
| ⌘   | command key   |
| ⌥   | otptin key    |
| ⎋   | escap key     |
| ⌫   | backspace key |
| ⌦   | delete key    |
| ↑   | up key        |
| →   | right key     |
| ←   | left key      |
| ↓   | down key      |
| ⇥   | tab key       |
| ⇧   | shift key     |
| ⇪   | capslock key  |
| ⌃   | control key   |
| ⏎   | reternkey key |

写文档的时候就可以这样写:

`⌘ + A`    全选

可能还有其他的 modifier key, 欢迎补充.

### 提供官网

nothing to reference

### 参考资料 URL

nothing to reference

**Comment by jaywcjlove** [comment]
@chen-bao-x 这个内容是要放在什么地方？

**Comment by chen-bao-x** [comment]
这里.  

Symbol Code 备忘清单  
https://wangchujiang.com/reference/docs/symbol-code.html  



不过这里面有一个  “技术符号” 区域有 ⌘ ,

当然要是有一个专门的 “键盘符号” 分区就更好了.

很开心收到你的回复.

**Comment by jaywcjlove** [comment]
@chen-bao-x 已添加

**Comment by chen-bao-x** [comment]
好快 ❤️
