### ISSUE TITLE
🐞 错误报告: mysql.md

### ISSUE THREAD

**Issue by Kaiyuan-Guo** [jaywcjlove/reference#827]
### 📄 错误清单

docs/mysql.md

### 🧨 错误类型

- [ ] 排版 & 文字错误
- [X] 清单内容示例错误
- [ ] 其它

### 📖 错误说明

将列c1重命名为c2不应该是：ALTER TABLE t1 RENAME c1 TO c2 ;
而是：ALTER TABLE t1 CHANGE c1 c2 datatype;

**Comment by jaywcjlove** [comment]
@Kaiyuan-Guo 好像这两种方法都可以的吧

```sql
ALTER TABLE t1 CHANGE c1 c2 datatype;
ALTER TABLE table_name RENAME COLUMN c1 TO c2;
```
