### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by sunxfancy** [jaywcjlove/reference#88]
1. 添加一个搜索栏支持搜索功能会更好，现在信息太多，找名字都找不过来
2. 做成chrome插件并添加到浏览器搜索中感觉会非常不错，或者做成浏览器起始页也不错。

**Comment by jaywcjlove** [comment]
@sunxfancy 预计会做一个搜索 #32 ，起始页不需要做成插件，浏览器设置一下就好，页面缓存到是可以做一下
