### ISSUE TITLE
错误报告: 页面源代码标签位置异常

### ISSUE THREAD

**Issue by coderkeel** [jaywcjlove/reference#9]
### 错误内容描述

如下图所示，源代码中，meta 相关标签应在 head 内，但实际在 body 标签内，导致页面 favicon 图标等无法展示。
<img width="754" alt="image" src="https://user-images.githubusercontent.com/13463757/198520712-207b1bb3-bb80-4b07-b7db-e1e29442e35f.png">

**Comment by xin6211** [comment]
编译后的index.html中head标签无任何内容

**Comment by jaywcjlove** [comment]
@xin6211 @coderkeel 看到了晚上修复它

**Comment by jaywcjlove** [comment]
@coderkeel @xin6211 修复完成

**Comment by xin6211** [comment]
> @coderkeel @xin6211 修复完成

辛苦啦
