### ISSUE TITLE
建议更名 jref 之类更独一无二的名字以便宣传

### ISSUE THREAD

**Issue by mofelee** [jaywcjlove/reference#90]
首先感谢付出，这个网站做的非常棒

项目的名字我觉得可以改为类似 jref, wref 之类的名称，1 是搜索引擎更容易搜到，2 是更容易被记住

如果能使用类似 jref.co/jref.info/jref.page 之类的短域名就更好了

另外 https://www.algolia.com/ 对开源项目提供免费的搜索引擎接入，
https://www.algolia.com/for-open-source/

**Comment by jaywcjlove** [comment]
@mofelee 

有计划添加添加一个搜索 https://github.com/jaywcjlove/reference/issues/32#issuecomment-1315053009，犹豫有离线本地搜索的需求，暂时应该不会添加 [algolia.com/](https://www.algolia.com/)

对于改名字这个建议非常好，reference 单词太通用了。

想了个 `cref` => <kbd>Chinese</kbd> + <kbd>reference</kbd> 中文参考缩写，但是...

好像没有太大必要，我仓库太多，过一段时间忘记了找不到这个仓库了...

短域名没有必要了，因为网站不挣钱不想投入，网站可以自己通过docker 本地部署。

感谢您的建议，谢谢 🙏

**Comment by mofelee** [comment]
我注册了一个 quickref.cn 指向了 https://wangchujiang.com/reference/ 
如果你需要可以转移给你，或者放我这，项目还在继续我会一直续费的

**Comment by jaywcjlove** [comment]
你可以使用 docker 部署个，因为 reference 在国内有时候打不开，gitee 也没有办法使用
@mofelee

**Comment by mofelee** [comment]
临时部署了一个 http://quickref.mofe.io
quickref.cn 还需要备案，估计下周才能搞好了

每天中国时间凌晨 4 点拉 main 分支的代码 build 并发布

**Comment by mofelee** [comment]
备案期间不能解析域名。。

**Comment by jaywcjlove** [comment]
@mofelee 你可以直接拉 gh-pages 分支编译好的静态页面，就不用费资源去编译了。
