### ISSUE TITLE
【备忘清单】 请求: 网站上可以增加导出PDF文档的方法吗？

### ISSUE THREAD

**Issue by WHJWNAVY** [jaywcjlove/reference#91]
网站上可以增加导出PDF文档的方法吗？

**Comment by jaywcjlove** [comment]
@WHJWNAVY 浏览器自带导出 pdf 功能，<kbd>command</kbd> + <kbd>p</kbd>

![image](https://user-images.githubusercontent.com/1680273/202074260-5428810c-e70c-4806-a0fe-e1c687a0c3f6.png)
