### ISSUE TITLE
请求添加备忘清单: Java8的新特性

### ISSUE THREAD

**Issue by whoms-yzt** [jaywcjlove/reference#97]
您可以在这里简单的提供一些资料，方便我们在 Quick Reference 中添加您想添加的备忘清单(速查表)。

【请您在这里介绍一下工具或者语言，这很重要】
可以加一些Java8的新特性

- [ ] 如果你有一张不错的备忘清单(速查表) [`参考这里`](https://github.com/jaywcjlove/reference/blob/main/CONTRIBUTING.md) 为仓库贡献。
- [x] 如果您不方便贡献，请在下方参考资料中提供链接地址，方便共建备忘清单(速查表)
- [ ] 这里为您提供了 Markdown 排版[示例教程](https://jaywcjlove.github.io/reference/docs/quickreference.html)

#### 提供参考资料地址

提供更多参考资料有助于我们整理成备忘清单(速查表)

- 参考地址 https://www.runoob.com/java/java8-new-features.html

_⚠️ 注意: 随着内容越来越多，可能甚至找不到这个工具或者语言的官网，请您在这里提供以便大家共同参与贡献内容_

**Comment by jaywcjlove** [comment]
@whoms-yzt 我觉得 Java8 新特性没有必要吧，现在还去介绍  2014 年 3 月 18 日发布 Java 8 的新特性？

**Comment by jaywcjlove** [comment]
现在 java 19 了，如果每个版本都介绍新特性一页就放不下了
